<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\external\dx-domain\src\Dx.Domain.Kernel\Dx.Domain.Kernel.csproj" />
    <ProjectReference Include="..\..\external\dx-domain\src\Dx.Domain.Primitives\Dx.Domain.Primitives.csproj" />
    <ProjectReference Include="..\..\external\dx-domain\src\Dx.Domain.Annotations\Dx.Domain.Annotations.csproj" />
  </ItemGroup>
</Project>
